# Generated by Django 4.1 on 2022-08-27 19:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_prestamo',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('total', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.tipoprestamo')),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
        migrations.CreateModel(
            name='MontoMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0)),
                ('tipo', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.tipocliente')),
            ],
            options={
                'db_table': 'MontoMax',
            },
        ),
    ]
