# Generated by Django 4.1 on 2022-08-27 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
