# Generated by Django 4.1 on 2022-08-27 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='employee_dni',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='employee_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='employee_surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='branch_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='branch_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='branch_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='employee_hire_date',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='branch_address_id',
        ),
        migrations.AddField(
            model_name='empleado',
            name='hire_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='address',
            field=models.OneToOneField(blank=True, db_column='address_id', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direcciones.direccion'),
        ),
    ]
