# Generated by Django 4.1 on 2022-08-28 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sucursales', '0002_rename_branch_id_empleado_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='employee_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='name',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='surname',
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
