# Generated by Django 4.1 on 2022-08-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marca_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_tarjeta',
            },
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='tarjeta_cvv',
            new_name='cvv',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='tarjeta_fecha_de_expiracion',
            new_name='fecha_de_expiracion',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='tarjeta_fecha_de_otorgamiento',
            new_name='fecha_de_otorgamiento',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='numero_tarjeta',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='marca',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarjetas.marcatarjeta'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarjetas.tipotarjeta'),
        ),
    ]
