# Generated by Django 4.1 on 2022-08-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_marcatarjeta_tipotarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_de_expiracion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_de_otorgamiento',
            field=models.DateField(null=True),
        ),
    ]
