# Generated by Django 4.1 on 2022-08-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='customer_dni',
            new_name='dni',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sucursales.sucursal'),
        ),
    ]
